version: '3'

services:
  db:
    image: 'postgres:12.2-alpine'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - net
  redis:
    image: redis
    ports:
    - "63797:6379"
    networks:
      - net

  nestjs:
    image: node:12-alpine
    working_dir: /pizza-store
    volumes:
      - ../:/pizza-store
    command: "npm run start:debug"
    ports:
      - "6225:3000"
      - "9229:9229"
    depends_on:
      - mysql
      - redis
    networks:
      - net
networks:
  net:
    driver: bridge

